name: Demo Actions
on: push
jobs:
  Explore-GitHub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh local package index
        run: sudo apt-update
      - name: 
        run: |
          DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -fOL "https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb"
          sudo apt install ./dive_${DIVE_VERSION}_linux_amd64.deb
    
